In [33]:
# Import Requisite Libraries
import numpy as np
import plotly as px
import pandas as pd
import sklearn as sk

In [34]:
# Read Data (Credit to Ai0, https://onedrive.live.com/view.aspx?resid=15C4097138751CAF%21721339&authkey=!AHKvMDy7MhWxN7g)
from pandas.api.types import CategoricalDtype
data = pd.read_excel("Cutoffs.xlsx", usecols = "C:K", names = ["Cutoffs", "Group", "Focus", "No", "Duration", "Cheerful Carnival", "Max Bonus", "Max Bonus (No Gacha)", "Max Bonus (No 4 Stars)"], dtype = {"Cheerful Carnival": CategoricalDtype()}, sheet_name = "T100", index_col = "No")

# Simplify Data
GROUPS = {"Mixed": "Mix", "Leo/Need": "L/N", "MORE MORE JUMP!": "MMJ", "Vivid BAD SQUAD": "VBS", "WonderlandsxShowtime": "WXS", "25-ji, Nightcord de": "N25"}
data.replace(GROUPS, inplace = True)

CHARAS = {"Hatsune Miku": "Miku", "Ichika Hoshino": "Ichika", "Saki Tenma": "Saki", "Honami Mochizuki": "Honami", "Shiho Hinomori": "Shiho", "Minori Hanasato": "Minori", "Haruka Kiritani": "Haruka", "Airi Momoi": "Airi", "Shizuku Hinomori": "Shizuku", "Kohane Azusawa": "Kohane", "An Shiraishi": "An", "Akito Shinonome": "Akito", "Toya Aoyagi": "Toya", "Tsukasa Tenma": "Tsukasa", "Emu Otori": "Emu", "Nene Kusanagi": "Nene", "Rui Kamishiro": "Rui", "Kanade Yoisaki": "Kanade", "Mafuyu Asahina": "Mafuyu", "Ena Shinonome": "Ena", "Mizuki Akiyama": "Mizuki"}
data.replace(CHARAS, inplace = True)

# Convert Data
data = pd.get_dummies(data, columns = ["Group", "Focus"])

# from sklearn.preprocessing import MinMaxScaler
# data = MinMaxScaler.fit_transform(data)

data.head()

,Cutoffs,Duration,Cheerful Carnival,Max Bonus,Max Bonus (No Gacha),Max Bonus (No 4 Stars),Group_L/N,Group_MMJ,Group_Mix,Group_N25,...,Focus_Miku,Focus_Minori,Focus_Mizuki,Focus_Nene,Focus_Rui,Focus_Saki,Focus_Shiho,Focus_Shizuku,Focus_Toya,Focus_Tsukasa
No,,,,,,,,,,,,,,,,,,,,,
39,34778378,9.25,True,3.55,2.5,2.25,False,False,False,True,...,False,False,True,False,False,False,False,False,False,False
66,30554984,8.25,True,3.85,2.5,2.00,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
74,27469602,8.25,False,3.85,2.5,2.50,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
72,24435438,9.25,True,4.05,2.5,2.50,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
77,20537929,8.25,False,3.85,2.5,2.50,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False